AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Serverless patterns - Amazon API Gateway to AWS Lambda to Amazon DynamoDB (uksb-1tthgi812) (tag:apigw-lambda-dynamodb)
Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Description: "Lambda function inserts data into DynamoDB table"
    Properties:
      FunctionName: list_chat_recording_segments
      Handler: list_chat_recording_segments.lambda_handler
      Runtime: python3.11
      CodeUri: src/
      Policies:
        DynamoDBCrudPolicy:
          TableName: !Ref DynamoDBTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: GET
  DynamoDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: todam_table
Outputs:
  EndpointUrl:
    Description: "HTTP REST endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
